// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPwX2zhF4LN929ukq66t0eDOZjH0_-df8',
    appId: '1:1014478472177:web:145a535f5e8ad5b14cfa50',
    messagingSenderId: '1014478472177',
    projectId: 'authtestnan',
    authDomain: 'authtestnan.firebaseapp.com',
    storageBucket: 'authtestnan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJiOBPOEccEgW6puHM9-NAuD70aH1nIDU',
    appId: '1:1014478472177:android:721b00c295f4a8c74cfa50',
    messagingSenderId: '1014478472177',
    projectId: 'authtestnan',
    storageBucket: 'authtestnan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBqh1enwI7HTz2gTRvQHmzJoUT40WbKQE',
    appId: '1:1014478472177:ios:78c784104c7822c74cfa50',
    messagingSenderId: '1014478472177',
    projectId: 'authtestnan',
    storageBucket: 'authtestnan.appspot.com',
    iosClientId: '1014478472177-cajmun8u01s8oss0a5mih24276lhqt3j.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBqh1enwI7HTz2gTRvQHmzJoUT40WbKQE',
    appId: '1:1014478472177:ios:1ec2c51e7193e7124cfa50',
    messagingSenderId: '1014478472177',
    projectId: 'authtestnan',
    storageBucket: 'authtestnan.appspot.com',
    iosClientId: '1014478472177-2a8htchpme1i22pq3pp79euqmcej51ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestApp.RunnerTests',
  );
}
